sudo: required
dist: trusty

branches:
  only: master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

matrix:
  include:
    - language: java
      jdk: oraclejdk8
      script:
        - ./mvnw clean install
      before_script:
        - cd ./Spring-Backend/

    - language: node_js
      node_js: stable
      install:
        - npm install
      before_install:
        - cd ./Angular-Frontend/
      script:
        - ng lint
        - ng test
        - ng build
