branches:
  only:
    - master

addons:
  chrome: stable

matrix:
  include:
    - language: python
      python: 3.8
      script:
        - pytest
      before_script:
        - cd ./NeuralNetwork/

    - language: java
      jdk: oraclejdk14
      script:
        - ./mvnw clean install
      before_script:
        - cd ./Spring-Backend/

    - language: node_js
      node_js: 
         - "12.17.0"
      install:
        - npm install
      before_install:
        - cd ./Angular-Frontend/
      script:
        - ng lint
        - ng test
        - ng build
